package com.newbieking.springtestgen.services

import com.newbieking.springtestgen.psi.EndpointMetadata
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Tests for AIProviderRegistry — multi-provider registration, priority ordering, and fallback.
 */
class AIProviderRegistryTest {

    // Stub provider for testing
    private class StubProvider(
        override val id: String,
        override val displayName: String,
        private val available: Boolean = true
    ) : AIProvider {

        override fun isAvailable(): Boolean = available

        override suspend fun generateMockRequestBody(
            metadata: EndpointMetadata,
            prompt: String
        ): AIGenerationResult {
            return AIGenerationResult(
                content = """{ "stub": "$id" }""",
                providerId = id,
                success = true,
                errorMessage = null,
                latencyMs = 10
            )
        }

        override suspend fun generateExpectedResponse(
            metadata: EndpointMetadata,
            prompt: String
        ): AIGenerationResult {
            return AIGenerationResult(
                content = """{ "response": "$id" }""",
                providerId = id,
                success = true,
                errorMessage = null,
                latencyMs = 10
            )
        }

        override suspend fun generateFromPrompt(prompt: String): AIGenerationResult {
            return AIGenerationResult(
                content = "generated by $id",
                providerId = id,
                success = true,
                errorMessage = null,
                latencyMs = 10
            )
        }
    }

    private fun makeConfig(id: String, priority: Int = 0, enabled: Boolean = true) = AIProviderConfig(
        id = id,
        displayName = "Provider $id",
        baseUrl = "https://api.$id.example.com",
        apiKey = "key-$id",
        model = "model-$id",
        priority = priority,
        enabled = enabled
    )

    // --- Registration tests ---

    @Test
    fun `register adds provider to registry`() {
        val registry = AIProviderRegistry(null) // null project for unit tests
        val provider = StubProvider("openai", "OpenAI")
        val config = makeConfig("openai")

        registry.register(provider, config)

        assertEquals(1, registry.getEnabledProviders().size)
        assertEquals("openai", registry.getEnabledProviders()[0].id)
    }

    @Test
    fun `register multiple providers sorts by priority`() {
        val registry = AIProviderRegistry(null)

        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai", priority = 10))
        registry.register(StubProvider("anthropic", "Anthropic"), makeConfig("anthropic", priority = 5))
        registry.register(StubProvider("local", "Local"), makeConfig("local", priority = 15))

        val providers = registry.getEnabledProviders()
        assertEquals(3, providers.size)
        // Lower priority value = higher precedence (sorted ascending)
        assertEquals("anthropic", providers[0].id)
        assertEquals("openai", providers[1].id)
        assertEquals("local", providers[2].id)
    }

    // --- Unregister tests ---

    @Test
    fun `unregister removes provider from registry`() {
        val registry = AIProviderRegistry(null)
        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai"))
        registry.register(StubProvider("anthropic", "Anthropic"), makeConfig("anthropic"))

        val removed = registry.unregister("openai")
        assertTrue(removed)
        assertEquals(1, registry.getEnabledProviders().size)
        assertEquals("anthropic", registry.getEnabledProviders()[0].id)
    }

    @Test
    fun `unregister non-existent provider returns false`() {
        val registry = AIProviderRegistry(null)
        val removed = registry.unregister("nonexistent")
        assertFalse(removed)
    }

    // --- Primary provider tests ---

    @Test
    fun `getPrimaryProvider returns highest priority enabled provider`() {
        val registry = AIProviderRegistry(null)
        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai", priority = 5))
        registry.register(StubProvider("anthropic", "Anthropic"), makeConfig("anthropic", priority = 10))

        val primary = registry.getPrimaryProvider()
        assertNotNull(primary)
        // Lower priority value = higher precedence
        assertEquals("openai", primary.id)
    }

    @Test
    fun `getPrimaryProvider returns null when no providers registered`() {
        val registry = AIProviderRegistry(null)
        assertNull(registry.getPrimaryProvider())
    }

    // --- Enabled/disabled tests ---

    @Test
    fun `disabled provider not in enabled list`() {
        val registry = AIProviderRegistry(null)
        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai", enabled = true))
        registry.register(StubProvider("anthropic", "Anthropic"), makeConfig("anthropic", enabled = false))

        val enabled = registry.getEnabledProviders()
        assertEquals(1, enabled.size)
        assertEquals("openai", enabled[0].id)
    }

    // --- Fallback provider tests ---

    @Test
    fun `getFallbackProviders returns all enabled providers except primary`() {
        val registry = AIProviderRegistry(null)
        registry.register(StubProvider("local", "Local"), makeConfig("local", priority = 1))
        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai", priority = 5))
        registry.register(StubProvider("anthropic", "Anthropic"), makeConfig("anthropic", priority = 10))

        val fallbacks = registry.getFallbackProviders()
        assertEquals(2, fallbacks.size)
        // local (priority=1) is primary, so excluded from fallbacks
        assertFalse(fallbacks.any { it.id == "local" })
    }

    @Test
    fun `getFallbackProviders returns empty when only one provider`() {
        val registry = AIProviderRegistry(null)
        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai"))

        val fallbacks = registry.getFallbackProviders()
        assertTrue(fallbacks.isEmpty())
    }

    // --- Reorder tests ---

    @Test
    fun `reorder changes provider priority order`() {
        val registry = AIProviderRegistry(null)
        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai", priority = 10))
        registry.register(StubProvider("anthropic", "Anthropic"), makeConfig("anthropic", priority = 5))

        // Reverse the order: anthropic first, then openai
        registry.reorder(listOf("anthropic", "openai"))

        val providers = registry.getEnabledProviders()
        assertEquals(2, providers.size)
        assertEquals("anthropic", providers[0].id)
        assertEquals("openai", providers[1].id)
    }

    // --- Update config tests ---

    @Test
    fun `updateConfig changes provider configuration`() {
        val registry = AIProviderRegistry(null)
        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai"))

        val newConfig = makeConfig("openai").copy(model = "gpt-4-turbo", timeoutSeconds = 60)
        registry.updateConfig(newConfig)

        // Provider should still be registered with updated config
        val provider = registry.getPrimaryProvider()
        assertNotNull(provider)
        assertEquals("openai", provider.id)
    }

    @Test
    fun `updateConfig disabling provider removes from enabled list`() {
        val registry = AIProviderRegistry(null)
        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai", enabled = true))

        val disabledConfig = makeConfig("openai", enabled = false)
        registry.updateConfig(disabledConfig)

        assertTrue(registry.getEnabledProviders().isEmpty())
    }

    // --- Edge cases ---

    @Test
    fun `re-registering same provider updates it`() {
        val registry = AIProviderRegistry(null)
        registry.register(StubProvider("openai", "OpenAI"), makeConfig("openai", priority = 5))
        registry.register(StubProvider("openai", "OpenAI v2"), makeConfig("openai", priority = 10))

        val providers = registry.getEnabledProviders()
        assertEquals(1, providers.size)
        assertEquals("OpenAI v2", providers[0].displayName)
    }
}